### ISSUE TITLE
NoSuchElementException

### ISSUE THREAD

**Issue by barrybecker4** [barrybecker4/ScalphaGoZero#1]
I saw this error while doing "sbt run".
Seems to be an intermittent problem.

```
[info]  Illegal move attempted at: (12,2)
[error] Exception in thread "main" java.util.NoSuchElementException: key not found: Play(Point(13,2))
[error]         at scala.collection.MapLike.default(MapLike.scala:232)
[error]         at scala.collection.MapLike.default$(MapLike.scala:231)
[error]         at scala.collection.AbstractMap.default(Map.scala:59)
[error]         at scala.collection.mutable.HashMap.apply(HashMap.scala:65)
[error]         at org.deeplearning4j.scalphagozero.agents.ZeroTreeNode.recordVisit(ZeroTreeNode.scala:43)
[error]         at org.deeplearning4j.scalphagozero.agents.ZeroAgent.$anonfun$selectMove$1(ZeroAgent.scala:42)
[error]         at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:156)
[error]         at org.deeplearning4j.scalphagozero.agents.ZeroAgent.selectMove(ZeroAgent.scala:30)
[error]         at org.deeplearning4j.scalphagozero.simulation.ZeroSimulator$.simulateGame(ZeroSimulator.scala:32)
[error]         at org.deeplearning4j.scalphagozero.demo.ScalphaGoZero$.$anonfun$main$1(ScalphaGoZero.scala:35)
[error]         at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:156)
[error]         at org.deeplearning4j.scalphagozero.demo.ScalphaGoZero$.main(ScalphaGoZero.scala:34)
[error]         at org.deeplearning4j.scalphagozero.demo.ScalphaGoZero.main(ScalphaGoZero.scala)
[error] Nonzero exit code returned from runner: 1
```

**Comment by barrybecker4** [comment]
fixed.
